[package]
name = "sentinel"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
fastbloom = "0.14.0"
lief = "0.17.1"
smartcore = "0.4.7"
walkdir = "2.5.0"
